version: 2
updates:
  - package-ecosystem: "pip"
    directory: "analyse"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    directory: "analyse"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
